
[[redirects]]
  from = "/api/*"
  to = "https://bwaka-production.up.railway.app/:splat"
  status = 200
  force = true
  headers = { X-From-Netlify = "true" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
